# Minimal Cloudflare Pages configuration
name = "connect"
compatibility_date = "2025-04-10"
main = "./_worker.js"

[site]
bucket = "./dist"

# Remove explicit build command since Pages will handle it
# [build]
# command = "npm run build" 