# Simple configuration for Cloudflare Pages
name = "connect"
compatibility_date = "2025-04-10"

[site]
bucket = "./dist"

# Remove explicit build command since Pages will handle it
# [build]
# command = "npm run build" 